# Tensor 생성
- 파이토치에서 데이터를 저장하는 자료구조
- ndarray와 성격, 사용법이 유사하다.

In [2]:
#np.array와 torch.tensor는 구조가 동일하다.

##  원하는 형태(shape) 텐서 생성
- **torch.tensor(자료구조 \[, dtype\])**
    - 지정한 dtype(Data type)에 맞는 Tensor객체를 생성해서 반환한다.
    - 
## 특정 타입의 Tensor를 직접 생성
- torch.tensor()로 생성하면서 dtype을 지정하면 아래 타입의 Tensor객체가 생성된다.
- 원하는 Type의 Tensor클래스를 이용해 직접 생성해도 된다.
- **torch.FloatTensor(자료구조)**
    - float32 타입 텐서 생성
- **torch.LongTensor(자료구조)** 
    - int64 타입 텐서생성
- 그외
    - BoolTensor(bool), CharTensor(int8), ShortTensor(int16), IntTensor(int32), DoubleTensor(float64)
    
## tensor 상태 조회
- **tensor.shape, tensor.size(\[축번호\])**
    -  tensor의 shape조회
- **tensor.dtype, tensor.type()**
    - tensor 원소들의 데이터타입 조회
    - dtype은 **data type**을 type()은 tensor **객체의 클래스 타입**을 반환한다.
- **tensor.ndim, tensor.dim()**  : tensor 차원
- **tensor.numel()**: 전체 원소 개수



In [2]:
import torch


torch.__version__

'2.1.0+cu118'

In [3]:
a = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
print("shape:", a.shape, a.size())
print("축별 크기:", a.shape[0], a.size(0))
print("type:", a.type(), a.dtype)
print('차원크기:', a.dim(), a.ndim)
print('원소개수:', a.numel())
print("device:", a.device) 

shape: torch.Size([2, 2]) torch.Size([2, 2])
축별 크기: 2 2
type: torch.FloatTensor torch.float32
차원크기: 2 2
원소개수: 4
device: cpu


In [6]:
torch.tensor(range(10))
#이것도 np.array와 구조가 유사하다.

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Float, Double(32, 64bit 실수)/Int, Long(32, 64 bit 정수) type Tensor
b = torch.FloatTensor([1,3,7])  #float32
print(b.dtype)
c = torch.IntTensor([10,20,30]) # int64
print(c.dtype)
d = torch.DoubleTensor([1, 2, 3]) #torch.tensor([],dtype=torch.float64)
print(d.dtype)
e = torch.LongTensor([10, 20, 30, 40]) #torch.tensor([],dtype=torch.int64)
print(e.dtype)

torch.float32
torch.int32
torch.float64
torch.int64


## 특정 값으로 구성된 Tensor 생성
- **torch.zeros(\*size), zeros_like(텐서)**: 0으로 구성된 tensor 생성
- **torch.ones(\*size), ones_like(텐서)**: 1로 구성된 tensor생성
- **torch.full(\*size), full_like(텐서)**: 지정한 값으로 구성된 tensor생성
    

In [9]:
torch.zeros(3,2,3)
# torch.ones(2,3)
# torch.full((3,2), fill_value=100)


tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [10]:
a = torch.tensor([[1, 2],[3,4]])
print(a.shape)
b = torch.zeros_like(a) #a와 같은 사이즈의, a로만 이뤄진 tensor 생성.
# b = torch.ones_like(a)
# b = torch.full_like(a, 20)
b.shape

torch.Size([2, 2])


torch.Size([2, 2])

## 동일한 간격으로 떨어진 값들로 구성된 배열생성
- **torch.arange(start=0, end, step=1)** 
- **torch.linspace(start, end, steps,)** : steps - 원소개수
- torch.arange나 torch.linspace는 넘파이의 그것과 구조가 완전히 동일하다.

In [11]:
torch.arange(10) #0에서부터 9까지!
# torch.arange(0, 1, 0.1)
# torch.arange(10, 1, -1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
torch.linspace(0, 10, 5) #0~10, 등분한값 5개
torch.linspace(0, 1, 11) #0~1, 등분한값 10개


tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

## 빈 tensor 생성
- **torch.empty(\*size)**
- 값이 아예 없을 수는 없으니, 그냥 의미 없는 값들로 채운다.

In [13]:
torch.empty(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## 난수를 이용한 생성

- **torch.rand(\*size)**: 0 ~ 1사이 실수로 구성된 배열을 생성. 각 값은 균등분포를 따른다.
- **torch.randn(\*size)**: 표준정규분포(평균:0, 표준편차:1)를 따르는 실수로 구성된 배열 생성
- **torch.randint(low=0, high, size)**: 지정한 범위의 정수로 구성된 배열 생성
- **torch.randperm(n)**: 0 ~ n 사이의 정수를 랜덤하게 섞은 값을 원소로 가지는 배열 생성

In [15]:
torch.manual_seed(1004)  # seed 설정
torch.rand(100,3)
torch.randn(3,3) #3개의 숫자를 정규분포 3으로 생성
torch.randint(1, 10, (3,3))  #범위는 1부터 10가지, 배열은 (3,3)
torch.randperm(5) #막상 5는 포함하지 않는다.

tensor([2, 3, 0, 4, 1])

## tensor를 상수로 변환
- tensor객체.item()
    - Scalar(상수) tensor를 python 상수로 변환

In [18]:
a = torch.tensor(10)
print(a,a.dtype,a.type())
print(a.item())

tensor(10) torch.int64 torch.LongTensor
10


In [20]:
idx = torch.randperm(9) #index를 섞어서 데이터를 섞는다.


In [21]:
a = torch.tensor(10)
print(a)
print(a.item())

tensor(10)
10


In [27]:
b = torch.tensor([20])
print(b)
print(b.shape) #size는 1이다.
print(b.item()) #원소가 하나인 배열 변환 가능

tensor([20])
torch.Size([1])
20


In [28]:
c = torch.tensor([1, 10, 100])
print(c,c.shape)
# print(c.item()) #원소가 여러개일 경우 Exception발생

tensor([  1,  10, 100]) torch.Size([3])


In [29]:
d = torch.tensor([10], device='cuda') #device="cuda" => VRAM에 저장한다. 
#근데 우리는 CUDA GPU가 없으니, 실행을 시키면 에러가 난다. 그러니 에러가 나도 그러려니 하자.
print(d)
print(d.item())

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

## ndarray 호환

- ndarray를 tensor로 생성(의외로 바꾸는 경우가 상당히 많다.)
    - **torch.tensor(ndarray)**
    - **torch.from_numpy(ndarray)**
- tensor를 ndarray로 변환
    - **tensor.numpy()**
    - tensor가 gpu에 있을 경우 cpu로 옮긴 뒤 변환해야 한다.

In [32]:
import numpy as np
import torch

In [33]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [35]:
# ndarray -> tensor
arr = np.arange(1,10)



#ndarray에서 tensor로 바꾸기 위해서는 아래의 2가지 방법 중 한가지를 쓰면 된다.
torch.tensor(arr)
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [37]:
# tensor -> ndarray
t = torch.randn(3,3) #random으로 생성하는 것.
print(t)
b=t.numpy()
print(type(b))
b

tensor([[-0.5668,  0.3922,  0.1592],
        [-1.3388,  0.6535,  0.6062],
        [ 0.0410, -0.5964,  1.1524]])
<class 'numpy.ndarray'>


array([[-0.56676835,  0.3922311 ,  0.15919687],
       [-1.3387808 ,  0.6534819 ,  0.6062082 ],
       [ 0.04101773, -0.596369  ,  1.152389  ]], dtype=float32)

In [38]:
t2 = torch.randn(2,2)
t2

tensor([[ 0.4826, -0.5480],
        [ 0.4243, -0.2416]])

In [39]:
#VRAM에 있는 Tensor 객체는 ndarray로 변환이 안된다.
#VRAM의 Tensor를 ram으로 이동시킨 뒤에 변환을 할 수 있다.
#t2.numpy()    #이 코드로 실행을 시키면 에러가 난다. 
t2.to("cpu").numpy() #이 코드는 텐서를 cpu로 옮기라고 하는 코드이다.

array([[ 0.48258954, -0.5479588 ],
       [ 0.42434272, -0.24164915]], dtype=float32)

## Tensor gpu/cpu 메모리로 옮기기

- pytorch는 데이터셋인 tensor를 cpu메모리와 gpu 메모리로 서로 옮길 수 있다.
    - 데이터에 대한 연산처리를 어디서 하느냐에 따라 메모리를 선택한다.
    - 장치는 문자열로 설정한다.
        - CPU 사용: "cpu"
        - nvida GPU: "cuda"
        - Apple m1: "mps"
            - pytorch 1.12 부터 지원
- 옮기기
    - tensor 생성시 `device` 파라미터를 이용해 설정
    - `tensor.to(device)`를 이용해 설정
- 현재 실행환경에서 어떤 장비를 사용할 수 있는지 확인
    - nvidia gpu 사용가능확인
        - `torch.cuda.is_available()` - nvida gpu 사용가능 여부
        - `torch.backends.mps.is_available()` - M1 사용가능 여부

In [ ]:
# device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

In [64]:
t = torch.tensor([1, 2, 3], dtype=torch.float32, device=device)
t

# t2 = t.to("cpu")
# t2

NameError: name 'device' is not defined

# 원소 조회및 변경 - indexing/slicing

- 대부분 Numpy 와 동일
    - **slicing에서 step을 <u>음수로 지정할 수 없다.</u>**


In [41]:
t = torch.randint(-10, 10, (100, ))
t

tensor([ -8,  -4,   1,  -6,  -3,  -2,   5,  -9,   2,  -9,  -9,   4,   0,   0,
          4,  -7,  -7,  -1,   7,  -7,  -2,   9,   5,  -1,  -2,   0,   8,   3,
          6,  -1, -10,  -2,  -4,  -6,  -2,   0,   3,   2,   8,   9,  -4,   4,
         -1,  -5,  -3,  -3,  -7,   3,  -5,   6,  -7,   1,  -9,   0,   3,   5,
         -6,  -6,   4,  -6,   5,   0,   5,   1,  -1,  -9,  -6,  -9,   2,   3,
          4,   0,  -7, -10,  -1,   5,   1,   8,   0,   9,   0,   7,   4,   6,
         -8,   5,   0,   2,  -4,  -5,   9,  -2, -10,   0,  -7,   9,   8,  -9,
         -6,  -6])

In [42]:
t[0], t[[1, 5, -1]]

(tensor(-8), tensor([-4, -2, -6]))

In [45]:
t[:5]
t[10:15]
t[90:]
t[3:30:3]
# t[10:1:-2]  #에러
t[1:10:2].flip(dims=(0,)) #reverse

tensor([-9, -9, -2, -6, -4])

In [46]:
# boolean index-----참인 것만 출력한다.
t[t > 0]

tensor([1, 5, 2, 4, 4, 7, 9, 5, 8, 3, 6, 3, 2, 8, 9, 4, 3, 6, 1, 3, 5, 4, 5, 5,
        1, 2, 3, 4, 5, 1, 8, 9, 7, 4, 6, 5, 2, 9, 9, 8])

In [47]:
# 변경 ---tensor도 값을 변경할 수 있다는 것만 기억하자.
t[0] = 100
t

tensor([100,  -4,   1,  -6,  -3,  -2,   5,  -9,   2,  -9,  -9,   4,   0,   0,
          4,  -7,  -7,  -1,   7,  -7,  -2,   9,   5,  -1,  -2,   0,   8,   3,
          6,  -1, -10,  -2,  -4,  -6,  -2,   0,   3,   2,   8,   9,  -4,   4,
         -1,  -5,  -3,  -3,  -7,   3,  -5,   6,  -7,   1,  -9,   0,   3,   5,
         -6,  -6,   4,  -6,   5,   0,   5,   1,  -1,  -9,  -6,  -9,   2,   3,
          4,   0,  -7, -10,  -1,   5,   1,   8,   0,   9,   0,   7,   4,   6,
         -8,   5,   0,   2,  -4,  -5,   9,  -2, -10,   0,  -7,   9,   8,  -9,
         -6,  -6])

In [48]:
t = torch.arange(1, 10).reshape(3,3)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [52]:
t[[1,0], [2,2]]  #(1,2), (0,2)의 값을 알아보자! 값을 조회하는 방법이 살짝 다를 수 있다. 그러니 혼동 주의.

t[0,2] #0행 2열의 값을 살펴보자! 그러면 값이 3이 나오는 것을 알 수 있다.

tensor(3)

# Reshape

## shape 변경
- tensor객체.reshape(\*shape) / view(\*shape) 이용
    - 변환 후 값을 변경하면 원본 배열의 값도 같이 바뀐다.
 > tensor.clone(): tensor를 복제한다.

In [53]:
a=torch.rand(12) #(12, )
a2 = a.reshape(3,4) #3*4
a3 = a.reshape((3,2,2)) #3*2*2
a4 = a.reshape((3,2,-1))  #한 개 axis는 -1로 설정가능하고 그럼 계산해서 알아서 설정해 준다. 숫자를 알아서 설정해준다는 거지.
print(a.shape, a2.size(), a3.shape, a4.shape)
               

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [54]:
#shape 대신 view를 썼는데, 두 메소드 중 어떤 것을 써도 효과는 동일하다.
a5 = a.view(3,4) 
a6 = a.view((3,2,2))
a7 = a.view((3,2,-1))  #한개 axis는 -1로 설정가능
print(a.shape, a5.size(), a6.shape, a7.shape)

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [56]:
a5[0, 0] = 12.1
a2[0, 1] = 15.1

print(a) 
#a5,a2의 값을 바뀌었는데 원본의 값이 바뀌었다. 그래서.... 이거는 얇은 복사라고 볼 수 있다.

tensor([12.1000, 15.1000,  0.4531,  0.1033,  0.2978,  0.7002,  0.0829,  0.5981,
         0.8110,  0.0473,  0.2827,  0.5073])


In [55]:
# tensor복사: clone() 메소드
r = a.clone().reshape(3,4)
r[0,0] = 100.1
print(a)
#r은 단순한 clone일 뿐이기 때문에, a의 값이 바뀌지 않는다.

tensor([0.4249, 0.9438, 0.4531, 0.1033, 0.2978, 0.7002, 0.0829, 0.5981, 0.8110,
        0.0473, 0.2827, 0.5073])


## dummy 축 늘리기

- None을 이용 (numpy의 newaxis 대신 None을 사용한다.)
- unsqueeze(dim=축번호)(squeeze는 줄이는 거니까. 반대지롱!)

In [58]:
import torch
a = torch.tensor([[10,20],[10,20]])
print(a.shape) #원본 shape는 (2,2)이다. 이를 잘 파악해두자.

a1, a2 = a[None, :], a.unsqueeze(dim=0) #늘어나는 곳에 none을 준다. 
print(a1.shape, a2.shape)

a3, a4 = a[:, :, None], a.unsqueeze(dim=-1)  #끝을 늘린다. dim을 통해 축번호를 설정한다.
print(a3.shape, a4.shape)

a5, a6 = a3[:,None,:,:], a3.unsqueeze(dim=1) #중간에 늘리는 것을 쏙 끼우는 느낌이다.
print(a5.shape, a6.shape)


#특이한 것은, unsqueeze와 None을 같이 사용한다는 것이다.
#unsqueeze와 dim 함수를 적절하게 쓰는 것이 좋다. 그래야 더 간단하게 할 수 있으니.

torch.Size([2, 2])
torch.Size([1, 2, 2]) torch.Size([1, 2, 2])
torch.Size([2, 2, 1]) torch.Size([2, 2, 1])
torch.Size([2, 1, 2, 1]) torch.Size([2, 1, 2, 1])


## dummy 축 제거
- squeeze(\[dim=축번호\]) 이용

In [60]:
t = torch.rand(3, 1, 3, 1)
print(t.shape)

r1 = t.squeeze()  #모두 제거
print(r1.shape)

r2 = t.squeeze(dim=1) # 특정 axis 제거
print(r2.shape)

r3 = t.squeeze(dim=[1,3]) # 여러 axis의 dummy 축 제거
print(r3.shape)

torch.Size([3, 1, 3, 1])
torch.Size([3, 3])
torch.Size([3, 3, 1])
torch.Size([3, 3])


## tensor 합치기
torch.cat([tensorA, tensorB, ...], dim=0)

In [61]:
a = torch.arange(10).reshape(2,5) #0-9
b = torch.arange(10,20).reshape(2,5) #10-19
c = torch.arange(20,30).reshape(2,5) #20-29
d = torch.arange(10,19).reshape(3,3) #10-18
print(a)
print(b)
print(c)
print(d)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])


In [62]:
torch.cat([a, b], dim=0) #합칠건데, 0번을 기준으로 합칠 것이다.

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [63]:
torch.cat([a, b, c], dim=0) #합칠건데, 0번을 기준으로 합칠 것이다. 그러면 2가 3번 '더해져서' (6,5)가 된다.

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])

In [64]:
torch.cat([a, b], axis=1) # dim 대신 axis사용가능
#가로로 그대로 늘어난다. 모양을 보면 알 수 있을 것이다.

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [65]:
torch.cat([a, b, c], axis=1) #-1은 마지막축이다!

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19, 25, 26, 27, 28, 29]])

In [66]:
 torch.cat([a, b], axis=-1) #음수는 뒤에서부터!

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [67]:
 torch.cat([a, d])  #Error가 난 이유는 합치려는 기준 축 이외의 축 size가 다르기 때문이다. (2,5)와 (3,3)

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 5 but got size 3 for tensor number 1 in the list.

## 값의 위치(index) 변경
- tensor 원소의 축별 index의 위치를 바꾼다.(간단히 생각하면 편하다.)
- `tensor.transpose(axis1, axis2)` 
    - 두 축의 자리만 변경 할 수 있다.
- `tensor.permute(axis1, axis2, axis3, ..)`
    - 두 개 이상의 축 자리를 변경한다.

In [68]:
a= torch.arange(12).reshape(4,3)
b= a.transpose(1,0) #index의 1축을 0축으로, 0축을 1축을 바꾼다.
print(a.shape,b.shape)
#변동

"""
[0,0]=>[0,0] #0,0은 축을 바꿔도 변함이 없다.
[0,1]=>[1,0] #0,1은 서로의 위치를 바꾼다.


"""

torch.Size([4, 3]) torch.Size([3, 4])


'\n[0,0]=>[0,0] #0,0은 축을 바꿔도 변함이 없다.\n[0,1]=>[1,0] #0,1은 서로의 위치를 바꾼다.\n\n\n'

In [70]:
X = torch.arange(24).reshape(2, 3, 4)
print(X.shape)
X

y = X.transpose(1, 2) #1번의 위치와 2번의 위치를 바꾼다.
print(y.shape)

z = X.permute(2, 0, 1) #2번 축을 0번 위치로, 0번축을 1번 위치로, 1번축을 2번 위치로 보낸다.
print(z.shape)

#transpose와 permute의 차이를 잘 보자. 그리고, 어떤 때에 뭘 써야 할지 잘 파악해두자.

torch.Size([2, 3, 4])
torch.Size([2, 4, 3])
torch.Size([4, 2, 3])


In [71]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [72]:
y

tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

In [73]:
z #x,y,z를 잘 파악해보자. 데이터가 미세하게 다르다는 것을 볼 수 있다.

tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])

# tensor 연산 및 주요 함수(곱하기, 나누기 등을 할 수 있다.)

## element-wise 연산
- tensor와 상수 연산시, tensor와 tensor간 연산시 원소별로 처리한다.
- 행렬곱 연산을 제외하고 tensor간 연산시 피연산지 tensor간에 shape이 같아야 한다.
    - shape이 다를 경우 조건이 맞으면 broadcasting을 한 뒤에 연산한다. (size가 다른 축의 경우 한개의 피연산자 size가 1일 경우 복사하여 shape을 맞춘다.)
    

In [74]:
import torch

a = torch.arange(10).reshape(2,5) 
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(50, 55)


#그냥 뭐.... 쭉 잘 봐라잉.
print(a)
print(b)
print(c)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([50, 51, 52, 53, 54])


In [75]:
print(a + 100) #모든 원소에 100을 더한다.
# print(a - 100)
# print(a < 5) #이거는 boolean이다.

tensor([[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109]])


In [76]:
print(a + b)
# print(a == b)

tensor([[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]])


In [77]:
# broadcasting
#데이터가 부족한 쪽에서, 데이터를 복제해서 dummy축을 만든다.
print(a + c) #결과를 보면, c측에서 한 줄을 또 만들어서 결과를 출력한다.

tensor([[50, 52, 54, 56, 58],
        [55, 57, 59, 61, 63]])


## 주요 연산함수

In [79]:
x=torch.arange(-4, 5).reshape(3,3)
print(x)
print(torch.abs(x)) #절대값
print(torch.sqrt(torch.abs(x))) #제곱근      #e**4 와 같이 하면 4제곱이 된다.
# print(torch.exp(x))  # torch.e**x
print(torch.log(torch.abs(x))) #밑이 e인 로그를 계산한다. 자연로그를 계산하는거지.
# print(torch.log(torch.exp(torch.tensor(1)))) # torch.log() 밑이 e인 로그계산
print(torch.log10(torch.tensor(10)))         # torch.log10() 밑이 10인 로그계산(계산 결과는 당연히 1이 나온다.)
print(torch.log2(torch.tensor(2)))           # torch.log2() 밑이 2인 로그계산(이거두!!)
# print("=====================")

tensor([[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]])
tensor([[4, 3, 2],
        [1, 0, 1],
        [2, 3, 4]])
tensor([[2.0000, 1.7321, 1.4142],
        [1.0000, 0.0000, 1.0000],
        [1.4142, 1.7321, 2.0000]])
tensor([[1.3863, 1.0986, 0.6931],
        [0.0000,   -inf, 0.0000],
        [0.6931, 1.0986, 1.3863]])
tensor(1.)
tensor(1.)


In [81]:
y = x + torch.randn((3,3))
print(y)
print(torch.round(y)) # 반올림 (하면 정수로 바뀐다.)
print(torch.round(y, decimals=2)) # 소수점 둘째자리까지. 그 이하에서 반올림!
print(torch.floor(y)) # 내림
print(torch.ceil(y)) # 올림


#이런 함수들을 가지고, 숫자가 너무 길게 나올 때, 숫자를 적절하게 cut하면 된다.

tensor([[-3.2288, -1.7263, -2.4652],
        [-0.9719,  0.6420,  1.7219],
        [ 1.4282,  3.5005,  3.5567]])
tensor([[-3., -2., -2.],
        [-1.,  1.,  2.],
        [ 1.,  4.,  4.]])
tensor([[-3.2300, -1.7300, -2.4700],
        [-0.9700,  0.6400,  1.7200],
        [ 1.4300,  3.5000,  3.5600]])
tensor([[-4., -2., -3.],
        [-1.,  0.,  1.],
        [ 1.,  3.,  3.]])
tensor([[-3., -1., -2.],
        [-0.,  1.,  2.],
        [ 2.,  4.,  4.]])


### 행렬곱
- `@` 연산자 또는 `torch.matmul(tensor1, tensor2)` 함수 이용

In [82]:
import torch

In [86]:
#tip: 다른 설명이 없다면, tensor는 floattensor이다.

x = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]
                      ])

y = torch.FloatTensor([[1, 2],
                       [1, 2],
                      ])
x.size(), y.shape

(torch.Size([3, 2]), torch.Size([2, 2]))

In [87]:
z1 = x @ y
z2 = torch.matmul(x, y)
print(z1.shape, z2.shape)
print(z1)
print(z2)

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])


In [89]:
# Batch 행렬곱(Batch matrix muliplication) - bmm()
# x, y가 가지는 3개의 2차원 배열 간에 행렬곱을 처리한다.
import torch
x = torch.FloatTensor(3,4,2)
y = torch.FloatTensor(3,2,5)
z = torch.bmm(x, y)
z.shape


#이 부분은 심화적인 부분에서 많이 쓰일 것 같으므로 일단 알아만 두자.

torch.Size([3, 4, 5])

## torch.nan, torch.inf
- nan: Not a Number, 주로 결측치를 표현한다.
- inf: infinit 무한. 
    - torch.inf: 양의 무한
    - -torch.inf: 음의 무한
- torch.isnan(tensor)
    - 원소별 결측치 확인
- torch.isinf(tensor)    
    - 원소별 inf 확인

In [90]:
print(torch.inf > 10, torch.inf < 10)
print(-torch.inf < 10, -torch.inf > 10)

True False
True False


In [92]:
print(torch.log(torch.tensor(-1))) # nan 
# print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))  # nan 여부 확인
# print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))  # inf 여부 확인

tensor(nan)


## 기술통계함수

In [94]:
X=torch.randn(3,4)
print(X)

tensor([[-1.6004,  1.1224, -0.4028,  0.6106],
        [-0.7580, -0.9758, -1.4271, -1.1446],
        [-1.0939, -0.4980,  2.3813,  0.0757]])


In [95]:
print(torch.sum(X))
print(torch.sum(X, dim=1)) #지정한 dim이나 axis의 index가 다른 값끼리 계선한다.
print(torch.sum(X, dim=1, keepdims=True))

tensor(-3.7104)
tensor([-0.2701, -4.3055,  0.8652])
tensor([[-0.2701],
        [-4.3055],
        [ 0.8652]])


In [96]:
print(torch.mean(X)) #이건 평균
print(torch.mean(X, dim=1))
print(torch.mean(X, dim=1, keepdims=True))

tensor(-0.3092)
tensor([-0.0675, -1.0764,  0.2163])
tensor([[-0.0675],
        [-1.0764],
        [ 0.2163]])


In [97]:
print(torch.std(X)) # standard deviation 표준 편차
print(torch.var(X)) # variance :분산
print(torch.var(X, dim=0))
print (torch.var(X,dim=0,keepdims=True))#차원을 유지해주면서 계산

tensor(1.1756)
tensor(1.3821)
tensor([0.1798, 1.2094, 3.8841, 0.8093])
tensor([[0.1798, 1.2094, 3.8841, 0.8093]])


In [103]:
print(X.sum(dim=1, keepdims=True))
print(X.mean(dim=1, keepdims=True))
print(X.std())

tensor([[-0.2701],
        [-4.3055],
        [ 0.8652]])
tensor([[-0.0675],
        [-1.0764],
        [ 0.2163]])
tensor(1.1756)


In [106]:
X #각각의 값을 출력한다.

tensor([[-1.6004,  1.1224, -0.4028,  0.6106],
        [-0.7580, -0.9758, -1.4271, -1.1446],
        [-1.0939, -0.4980,  2.3813,  0.0757]])

In [107]:
print(torch.max(X))
print(torch.max(X, dim=0))  # return_types.max 타입객체로 반환. max값과 max값의 index를 묶어서 반환
#각 분야에서 MAX인 것을 출력한다.
# print(torch.max(X, dim=1))
# print(torch.max(X, dim=1).values, torch.max(X, dim=1).indices, sep=" || ") #indices는 '지수'라는 의미이다.
# print(torch.max(X, dim=0, keepdims=True))  #keepdims=True : 차원(rank)를 유지 
# # print(torch.max(X, dim=1, keepdims=True))

tensor(2.3813)
torch.return_types.max(
values=tensor([-0.7580,  1.1224,  2.3813,  0.6106]),
indices=tensor([1, 0, 2, 0]))


In [110]:
print(torch.min(X))
print(torch.min(X, dim=0))
print(torch.min(X, dim=1))

print(torch.argmax(X))
print(torch.argmax(X, dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(X, dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor(-1.6004)
torch.return_types.min(
values=tensor([-1.6004, -0.9758, -1.4271, -1.1446]),
indices=tensor([0, 1, 1, 1]))
torch.return_types.min(
values=tensor([-1.6004, -1.4271, -1.0939]),
indices=tensor([0, 2, 0]))
tensor(10)
tensor([1, 0, 2, 0])
tensor([1, 0, 2])


# autograd(자동미분)
- 자동 미분을 이용해 gradient를 계산하는 pytorch system.
- 딥러닝 모델에서 weight와 bias tensor들(Parameter)은 backpropagation(역전파)를 이용해 gradient를 구해서 loss가 줄어드는 방향으로 update를 하게된다.
- pytorch는 이런 미분 수행을 자동으로 처리해 준다.
    - gradient(기울기)를 구한다는 것은 미분을 한다는 것을 말한다.
- tensor가 미분 가능하려면 `requires_grad=True` 로 설정되 있어야 한다. (default: False)
    

In [116]:
x = torch.tensor([1.], requires_grad=True) #requires_grad가 true로 설정이 되어야 한다!
# x = torch.tensor([1.])
# x.requires_grad = True
print(x) #출력창에 requires_grad=True 가 안뜨면 false라는 의미이다.
print(x.requires_grad) 

tensor([1.], requires_grad=True)
True


In [117]:
y = x ** 2
print(y)
# 계산 결과를 담은 tensor인 y는 계산 결과와 grad_fn에 어떤 계산을 했는지 정보를 담고 있다. (PowBackward0)
# 이는 y 계산에 사용된 x가 requires_grad=True이기 때문이다.

tensor([1.], grad_fn=<PowBackward0>)


In [118]:
# 미분 - tensor.backward() 호출
y.backward()   # dy/dx  gradient 계산 후 결과를 x의 grad attribute에 저장한다.
#y가 적혀 있지만, 결국에는 x값을 미분하는 것이다. 잘 모르겠다면, 수학시간에 배웠던 것들을 생각해 보자.
#결과를 x에 저장한다는 것이 매우 신기하다.
#backward는 역전파, forward는 순전파를 의미한다. 
#역전파는 미분을 의미한다.

#미분이 더 안되는데 하면 에러가 당연히 난다. 주의!

In [119]:
x.grad
# 도함수: y` = 2x 이고 x가 1이었으므로 grad는 2

tensor([2.])

In [120]:
# requires_grad가 True로 설정되어 있지 않은 경우
x = torch.tensor([1.])
y = x ** 2
print(x)
y.backward() #윗줄까지는 프린트가 잘 되는데, 도함수가 없으니 계산을 할 수 없어 에러가 난다.

tensor([1.])


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [121]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2   # 미분: 2x
z = y * 10   # 미분: 10  ===> 2x * 10
#근데 이 구조를 잘 보면, x가 바뀌어야 다른 값들이 바뀐다.

#y값에 따라서 z의 결과가 바뀐다.
print(y,y.requires_grad)
z.backward()#z와 y의 미분, y와 x의 미분을 서로 계산하면, z와 x의 미분을 알 수 있다. 결과적으로, 이는 x에 대한 계산이다.
print(z)
print(x.grad) #미분이 잘 된 것을 볼 수 있다.

tensor([1.], grad_fn=<PowBackward0>) True
tensor([10.], grad_fn=<MulBackward0>)
tensor([20.])


In [124]:
## 편미분(간단히 말해서, x와 y가 따로 있는데, 1개의 변수만 미분하는 것이다.)
#x에 대해 미분을 한다 치면, y는 그냥 상수로 봐버리는 것이다.
x=torch.tensor([1.],requires_grad=True)
y=torch.tensor([1.],requires_grad=True)
z= 2*x**2 + y**2
print(z)
z.backward() #이것도 결국 x가 바뀌는 것에 대해 값을 구하는 것이다.
print(x.grad)  #dz/dx ===>y를 상수로 처리를 해서, 값이 4가 나온다.
print(y.grad)  #dz/dy ====>x를 상수로 처리를 해서, 값이 2가 나온다.

tensor([3.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([2.])


In [129]:
#함수가 다르더라도 과정은 대강 같다.
x=torch.tensor([1., 2., 3.] ,requires_grad=True)
y=torch.sum(x**2) # [x1**2 + x2**2 + x3**2]  
y.backward() #[dy/dx1, dy/dx2, dy/dx3] = [2x1, 2x2, 2x3]

print(y) 
print(x.grad) # 스칼라를 벡터로 미분

tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


## torch.no_grad() 
- no_grad() 구문에서 연산을 할 경우 requires_grad=True로 설정되었다 하더라도 gradient를 update하지 않는다.
- gradient를 계산하지 말라는 의미. 즉, 미분을 하지 말라는 의미이다.
- 딥러닝 모델 학습이 끝나고 평가할 때는 gradient를 계산할 필요가 없기 때문에 no_grad 구문을 사용한다.(중요!!)
- 그리고, 이걸 한다고 해서, 다른 결과가 나오는 것은 아니니, 이를 문제없이 써도 된다.


In [131]:
x = torch.tensor(1.0, requires_grad = True) #requires_grad를 True로 해야만 미분 계산이 가능하다.
print(x.requires_grad)

y = x**2

print(y.requires_grad)  # 연산이 결과 requires_grad도 True -> 그래야 미분이 가능하므로. x가 true이면 y도 true이다.
print(x.requires_grad)
print(y)

y.backward() #뭔가 아직은 이 코드가 익숙하지는 않은데, 그래도 익숙해져라.
print(x.grad) #연산 결과 (2)가 나온다. 이는 앞에서 했던 것이다.



True
True
True
tensor(1., grad_fn=<PowBackward0>)
tensor(2.)


In [132]:
x = torch.tensor(1.0, requires_grad = True)
print(x.requires_grad)

with torch.no_grad(): #다른 것은 다 동일한데, with 구문을 통해 no_grad를 적용시킨다. 
    #no_grad 안에서 y를 적용을 시키면, requires_grad가 false가 나온다.
    print(x.requires_grad)
    y = x**2 #torch.no_grad()로 인해서 도함수를 만들지 않는다.
    print(y.requires_grad)# 연산이 적용될 때 requires_grad가 False가 된다.
    print(y)
    
print(x.requires_grad)
# y.backward() #no_grad를 적용한 상태로 y.backward를 적용시키려 하면 에러(exception)가 난다.


True
True
False
tensor(1.)
True


## gradient 값 초기화

In [59]:
x = torch.tensor(1., requires_grad=True)
y = x**2
y.backward()
print("x의 gradient값:", x.grad ) #y.backward가 끝이 나면, x.grad의 값이 2로 update된다.

x의 gradient값: tensor(2.)


In [ ]:
x

In [62]:
z = x **2
z.backward()
print("x의 gradient값:", x.grad )
#얼레? 틀린 값이 나오네? 이는 grad값이 이미 위의 연산에 있었기 때문이다. 계산을 계속하면 값이 계속 2씩 증가할 것이다.

x의 gradient값: tensor(8.)


In [63]:
x = torch.tensor(1., requires_grad=True)
y = x**2
y.backward()
x.grad

tensor(2.)

In [66]:
# gradient초기화 grad를 tensor 재정의로 다시 정의한다. (중요한 내용-----잘 숙지할것!)
x.grad = torch.tensor(0.)   
z = x**2
z.backward()
x.grad
#앞에서 초기화를 했기 때문에 grad의 값이 계속 2가 나온다!

tensor(2.)