# LinearRegression from Scratch


# 구현할 것
- 공부시간과 성적간의 관계를 모델링한다.
    - **머신러닝 모델(모형)이란** 수집한 데이터를 기반으로 입력값(Feature)와 출력값(Target)간의 관계를 하나의 공식으로 정의한 함수이다. 그 공식을 찾는 과정을 **모델링**이라고 한다.
    - 이 예제에서는 공부한 시간으로 점수를 예측하는 모델을 정의한다.
    - 입력값과 출력값 간의 관계를 정의할 수있는 다양한 함수(공식)이 있다. 여기에서는 딥러닝과 관계가 있는 **Linear Regression** 을 사용해본다.

# 데이터 확인
- 입력데이터: 공부시간
- 출력데이터: 성적

|공부시간|점수|
|-|-|
|1|20|
|2|40|
|3|60|

우리가 수집한 공부시간과 점수 데이터를 바탕으로 둘 간의 관계를 식으로 정의 할 수 있으면 **내가 몇시간 공부하면 점수를 얼마 받을 수 있는지 예측할 수 있게 된다.**   
수집한 데이터를 기반으로 앞으로 예측할 수있는 모형을 만드는 것이 머신러닝 모델링이다. 예측을 하기 위해서는 데이터를 '쏟아 붓는다'

  

## 학습(훈련) 데이터셋 만들기
- 모델을 학습시키기 위한 데이터셋을 구성한다.
- 입력데이터와 출력데이터을 따로 행렬로 구성한다.
- 같은 데이터 포인트의 입력, 출력 데이터를 같은 index에 정의한다.

# 모델링

## 모델 정의

- Feature와 Target간의 관계를 수식으로 정의한다.
- 여기서는 공부시간(Feature)와 점수(Target)간의 관계를 정의하는데 **선형회귀(Linear Regression) 모델** 을 가설로 세우고 모델링을 한다.
    - 많은 머신러닝 연구자들이 다양한 종류의 데이터에 관계를 예측할 수 있는 여러 알고리즘을 연구했다.
    - 선형회귀 모델은 입력데이터와 출력데이터가 선형관계(비례 또는 반비례 관계)일때 좋은 성능을 나타낸다.
  
> ### 가설
> - 아직은 이 식이 맞는지 틀린지는 알 수없기 때문에 **이 식을 가설(hypothesis) 라고 한다.**
> - 가설을 세우고 모델링을 한 뒤 검증을 해서 좋은 예측결과를 내면 그 가설을 최종 결과 모델로 결정한다. 예측결과가 좋지 않을 경우 새로운 가설로 모델링을 한다.
 
  

### 선형회귀 (Linear Regression)
- Feature들의 가중합을 이용해 Target을 추정한다.
- Feature에 곱해지는 가중치(weight)들은 각 Feature가 Target 얼마나 영향을 주는지 영향도가 된다.
    - 음수일 경우는 target값을 줄이고 양수일 경우는 target값을 늘린다.
    - 가중치가 0에 가까울 수록 target에 영향을 주지 않는 feature이고 0에서 멀수록 target에 많은 영향을 주는 target이 된다.
- 모델 학습과정에서 가장 적절한 Feature의 가중치를 찾아야 한다.
- 한 마디로, 랜덤한 값을 이용해서 방정식을 잘 찾아내는 것이다.
- 관련 도서를 찾는 것도 도움이 된다!
 
$$
\hat{y} = Wx + b
$$
<center>$\hat{y}$: 모델추정값<br>W: 가중치<br>x: Feature<br>b: bias(편향)</center>


## [경사하강법을 이용한 최적화](03_2_gradient_decending.ipynb)

- 반드시 반드시 반드시 반드시 복습하기!!


## 파이토치로 구현

In [1]:
import torch #이거 빼먹지 말자.

In [2]:


#훈련(train) 데이터 정의
#입력데이터 변수명: X, 출력데이터 변수명:Y
X_train = torch.tensor([
    [1],[2],[3]
],dtype=torch.float32)


y_train  = torch.tensor([[20],[40],[60]],dtype=torch.float32)


#순서대로 1시간 공부-점수(20)/2시간 공부-점수(40)....뭐 이렇게 구성되어 있다.

In [3]:
print(X_train.shape,y_train.shape)

#[3,1] => [데이터개수,개별데이터의 shape] => 3개의 데이터. 각 데이터는 1개의 값을 구성된 1차원배열


torch.Size([3, 1]) torch.Size([3, 1])


In [5]:
#함수를 하나 만들 것이다.
#이 함수는 weight와 bias를 정의하는 것이다.


#그 전에,seed값을 잘 적용시켜서 랜덤값을 동일하게 고정시키자.
torch.manual_seed(0)


#각 변수들을 정의하자.(randn을 통해 정규분포를 만족하는 놈을 출력한다.)
weight = torch.randn(1,1,requires_grad=True) #(1:입력 feature 개수,1:출력 값의 개수)
#requires_grad를 통해 값을 변동시킬 것을 암시한다.

bias = torch.randn(1,requires_grad=True)
#bias도 바뀌어야 하는 대상이므로 requires_grad을 True라고 한다.


print("초기 파라미터")
print("weight:", weight)
print("bias:",bias)

def linear_model(X):
    pred = X@weight+bias #계산을 진행한다. weight와 bias는 새로 만든 것이다.
    return pred


초기 파라미터
weight: tensor([[1.5410]], requires_grad=True)
bias: tensor([-0.2934], requires_grad=True)


In [6]:
### 예측

pred_train = linear_model(X_train) #공부시간에 따른 예측점수라고 볼 수 있다.
pred_train  #공부시간에 따른 예측 점수를 알 수 있다.


tensor([[1.2476],
        [2.7886],
        [4.3296]], grad_fn=<AddBackward0>)

In [8]:
#어? 근데 실제 점수(y_train)는 예측 결과와 오차가 꽤 많이 난다.
#그래서! 오차함수라는 것을 정의한다.


#오차함수: 모델이 추론한 값과 정답사이의 차이를 계산한다.
#평균 제곱 오차(mean squared error:MSE) -----앞자리를 따서 MSE라고 한다.

def mse_lose_fn(pred:"예측값",y:"정답"):
    return torch.mean((pred-y)**2) #평균 제곱 오차이니깐....!
    #torch.mean을 통해 평균 제곱 오차를 계산한다.
    
    

In [9]:
loss = mse_lose_fn(pred_train,y_train)
print('오차:',loss)
#오차를 적나라하게 볼 수 있다.

오차: tensor(1611.8477, grad_fn=<MeanBackward0>)


In [10]:
#미분계수를 계산한다.
loss.backward()

In [12]:
print("weight의 grad::",weight.grad)
print("bias의 grad:",bias.grad)

weight의 grad:: tensor([[-173.4578]])
bias의 grad: tensor([-74.4229])


In [15]:
###최적화 -> 경사하강법 ====>파이토치의 함수를 사용한다.
#torch.optim.SGD라는 함수의 구조를 잘 파악하자.
optimizer = torch.optim.SGD([weight,bias],
                           lr=0.001 #학습률
                           ) #최적화할 대상 => requires_grad가 True여야 한다.

#경사하강법 계산 연산을 처리한다. weight와 bias가 바뀌는 것을 잘 파악하자.
print("update전 weight:",weight)
optimizer.step()
print("update후 weight:",weight)

#계속 셀을 실행을 하면, tensor안의 값이 바뀌는 것을 볼 수 있다.

update전 weight: tensor([[1.8879]], requires_grad=True)
update후 weight: tensor([[2.0614]], requires_grad=True)


In [17]:
###업데이트 후 로스 계산

#추론
pred = linear_model(X_train)

#오차 계산
loss2 = mse_lose_fn(pred,X_train)


print("이전:",loss)
print("업데이트 후:",loss2)
#오차가 매우 줄어들었음을 알 수 있다.


이전: tensor(1611.8477, grad_fn=<MeanBackward0>)
업데이트 후: tensor(4.9641, grad_fn=<MeanBackward0>)


### 모델링

### 학습
1. 모델을 이용해 추정한다.
   - pred = model(input)
1. loss를 계산한다.
   - loss = loss_fn(pred, target)
1. 계산된 loss를 파라미터에 대해 미분하여 계산한 gradient 값을 각 파라미터에 저장한다.
   - loss.backward()
1. optimizer를 이용해 파라미터를 update한다. (반복문 안에서의 로직을 처리해주는 것이 바로 optimizer이다.)
   - optimizer.step()  
1. 파라미터의 gradient(미분값)을 0으로 초기화한다.
   - optimizer.zero_grad()
- 위의 단계를 반복한다.   

In [18]:
#과정이 어렵다. 복습을 반드시 하도록 하자!!
#몇 번 돌려야 좋은지 모르기 때문에, 많든 적든 시행착오를 겪어봐야 한다.

STEPS = 100 #파라미터(WEIGHT,BIAS)를 업데이트할 횟수.
for _ in range(STEPS):
    #1.추론
    pred = linear_model(X_train)
    # 2.오차 계산
    loss = mse_lose_fn(pred,y_train)
    
    #3.weight와 bias에 대한 gredient를 계산한다.
    loss.backward()
    
    #4.최적화: optimizer를 이용한다. 알고리즘은 경사하강법을 쓴다. 
    optimizer.step()
    
    #5.계산된 gradient 값을 초기화한다. 
    optimizer.zero_grad()
    

#함수 자체는 금방 끝난다.

In [20]:
###weight, bias 값
#값들이 많이 업데이트 된 것을 알 수 있다.
print("weight",weight)
print("bias:",bias)

weight tensor([[12.3091]], requires_grad=True)
bias: tensor([4.2502], requires_grad=True)


In [22]:
#오차 계산
pred3 = linear_model(X_train)
loss3 = mse_lose_fn(pred3,y_train)

print(loss3)

tensor(163.3457, grad_fn=<MeanBackward0>)


In [24]:
163.3457**(1/2) #오차가 13 정도로 많이 줄어들었음을 알 수 있다.
#위의 과정들을 계속 하면 결과적인 오차 값이 계속해서 작아짐을 볼 수 있다.

12.780676820888633

# 다중 입력, 다중 출력
- 다중입력: Feature가 여러개인 경우
- 다중출력: Output 결과가 여러개인 경우

다음 가상 데이터를 이용해 사과와 오렌지 수확량을 예측하는 선형회귀 모델을 정의한다.  
[참조](https://www.kaggle.com/code/aakashns/pytorch-basics-linear-regression-from-scratch)


|온도(F)|강수량(mm)|습도(%)|사과생산량(ton)|오렌지생산량|
|-|-|-|-:|-:|
|73|67|43|56|70|
|91|88|64|81|101|
|87|134|58|119|133|
|102|43|37|22|37|
|69|96|70|103|119|

```
사과수확량  = w11 * 온도 + w12 * 강수량 + w13 * 습도 + b1
오렌지수확량 = w21 * 온도 + w22 * 강수량 + w23 *습도 + b2
```

- `온도`, `강수량`, `습도` 값이 사과와, 오렌지 수확량에 어느정도 영향을 주는지 가중치를 찾는다.
    - 모델은 사과의 수확량, 오렌지의 수확량 **두개의 예측결과를 출력**해야 한다.
    - 사과에 대해 예측하기 위한 weight 3개와 오렌지에 대해 예측하기 위한 weight 3개 이렇게 두 묶음, 총 6개의 weight를 정의하고 학습을 통해 가장 적당한 값을 찾는다.
        - 이 묶음을 딥러닝에서는 **Node, Unit, Neuron** 이라고 한다.
- 목적은 우리가 수집한 train 데이터셋을 이용해 **정확한 예측을 위한 weight와 bias**를 찾는 것이다.

In [4]:
#한 마디로, 여러 개의 요소를 잘 파악해서 생산량을 예측하는 것이다.
#보통, 우리가 추론하는 값은 1개인 경우가 많은데, 이 경우에는 2개이다. 그래도 뭐 큰 문제는 없다.
#각 요소의 weight의 절대값이 크고 작음에 따라 수확량에 영향을 준다. 부정적인 영향이든 좋은 영향이든 상관은 없다.
#변수가 3개이므로 가중치(w)도 3개가 필요하다. 근데 오렌지 뿐만 아니라, 사과도 있잖아? 그래서 결국은 3*2이다.



#

## Training Data
- Train data는 feature와 target를 각각 따로 2개의 행렬로 구성한다.
- Feature의 행은 관측치(개별 데이터)를 열을 Feature(특성, 변수)를 표현한다.
- Target은 모델이 예측할 대상으로 행은 개별 관측치, 열은 각 항목에 대한 정답으로 이 예제에서는 사과수확량과 오렌지 수확량 값을 가진다.

In [61]:
import torch
# Input (temp, rainfall, humidity) : (5, 3)
#위의 그래프의 데이터들과 비교해 보는 것이 좋다. 그러면 이해가 빨라.
inputs = torch.tensor([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype=torch.float32)

In [62]:
# Targets: 생산량 - (apples, oranges) - (5, 2)
targets = torch.tensor([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype=torch.float32)

## Linear Regression Model (from scratch)

### weight와 bias
- weight 는 각 feature에 곱해지는 가중치로 target 값에 얼마나 영향을 주는지를 나타낸다. 직선의 방정식에서 기울기이다.
- bias는 각 feature와 weight간의 가중합에 더해주는 값으로 모든 feature가 0일 경우 target의 값을 나타낸다. 직선의 방정식에서 절편이다.
- weight와 bias는 각각 random 값을 초기값으로 가지는 matrix로 정의한다.
- weight의 shape: (2, 3)
- bias의 shape: (2, ) 

In [63]:
torch.manual_seed(0)


### weight와 bias 생성

weights = torch.randn(3,2,requires_grad=True) #학습을 통해 찾아야 하는 것이기 때문에 true이다.
##[3,2]===>3은 input feature이고 2는 output feature의 개수이다. ===>[[온도weight,강수weight,습도weight],[사과,오렌지]]


bias = torch.randn(2,requires_grad=True) #이것도 requires_grad를 True로 한다.
#[2] =[output개수=> 사과,오렌지]





In [64]:
print(weights.shape,bias.shape)
print(weights)
print(bias)

torch.Size([3, 2]) torch.Size([2])
tensor([[ 1.5410, -0.2934],
        [-2.1788,  0.5684],
        [-1.0845, -1.3986]], requires_grad=True)
tensor([0.4033, 0.8380], requires_grad=True)


### Linear Regression model
모델은 weights `w`와 inputs `x`의 내적(dot product)한 값에 bias `b`를 더하는 간단한 함수이다. 

$$
\hspace{2.5cm} X \hspace{1.1cm} \cdot \hspace{1.2cm} W^T \hspace{1.2cm}  + \hspace{1cm} b \hspace{2cm}
$$

$$
\left[ \begin{array}{cc}
73 & 67 & 43 \\
91 & 88 & 64 \\
\vdots & \vdots & \vdots \\
69 & 96 & 70
\end{array} \right]
%
\cdot
%
\left[ \begin{array}{cc}
w_{11} & w_{21} \\
w_{12} & w_{22} \\
w_{13} & w_{23}
\end{array} \right]
%
+
%
\left[ \begin{array}{cc}
b_{1} & b_{2} \\
b_{1} & b_{2} \\
\vdots & \vdots \\
b_{1} & b_{2} \\
\end{array} \right]
$$

In [65]:
#위의 linear regression model이 계산을 간단하게 해 주는 식이다. 


def model(X):
    return X @ weights + bias

In [66]:
#위의 식을 직접 계산해 준다.
pred = model(inputs)
print(pred)
#size는 5,2이고, 사과와 오렌지에 대한 5개 쌍이 나온다.
#딱 봐도 값이 틀렸다 ㅋㅋ

tensor([[ -79.7173,  -42.6370],
        [-120.5089,  -65.3522],
        [-220.3900,  -29.6390],
        [  23.7697,  -56.3972],
        [-178.3483,  -62.7408]], grad_fn=<AddBackward0>)


## Loss Function
모델이 예측한 값과 정답간의 차이를 비교하는 메소드. 

In [67]:
def mse_loss_fn(preds,targets):
    squared_error = (preds-targets)**2
    return torch.mean(squared_error) 
    

In [68]:
loss = mse_loss_fn(pred,targets)#사과생산량 오차와 오렌지 생산량 오차를 합친 값이 나온다.
loss

tensor(36193.4961, grad_fn=<MeanBackward0>)

## Gradients 계산
loss에 대한 weight와 bias의 gradients (미분계수)를 계산한다. **Pytorch의 자동미분**을 이용한다. (**graident를 구하려는 tensor는 requires_grad=True로 설정한다.**)

In [69]:
#그냥 간단하게 loss.backward를 해 주면 된다.

loss.backward()

In [70]:
print(weights)
print(weights.grad) #각각에 대한 grad 값이 구해졌다. 이는 loss.backward에 따라 구해졌다.

tensor([[ 1.5410, -0.2934],
        [-2.1788,  0.5684],
        [-1.0845, -1.3986]], requires_grad=True)
tensor([[-15400.8262, -11915.3555],
        [-19847.4922, -13088.5000],
        [-11609.1875,  -8220.1094]])


In [71]:
new_weight_0_0 = weights[0,0] - weights.grad[0,0]*0.001
new_weight_0_0 #값이 새롭게 바뀐다.(이런 과정으로 값이 바뀐다고 보면 된다.)

tensor(16.9418, grad_fn=<SubBackward0>)

In [72]:
print(bias)
print(bias.grad) #grad를 구하니, 값이 많이 바뀌었다.

#앞으로 , grad값을 100분의 1을 한 것을 계속 bias에 더해서 값을 구해갈 것이다.

tensor([0.4033, 0.8380], requires_grad=True)
tensor([-191.2390, -143.3532])


## 모델 최적화
gradient decent 알고리즘을 이용해 loss를 줄여 모델의 추론 성능을 높인다. 이를 위해 좋은 성능을 낼 수 있도록 **경사하강법(gradient decent)** 을 이용해 weight와 bias를 update한다. 

1. 추론하기
2. loss 계산하기
3. weight와 bias에 대한 gradient계산하기
4. 계산된 gradient에 비례한 값을 학습률을 곱해 작게 만든 뒤 wegith에서 빼서 조정한다.
5. gradient를 0으로 초기화

In [73]:
#step(파라미터 업데이트 횟수)수 지정
STEPS =100 #파라미터를 100번 업데이트 하겠다는 의미이다.

#학습률(learning rate)
LR = 0.0001 #1e-4 로 해도 된다.


#Optimizer 생성
optimizer = torch.optim.SGD([weights,bias],lr=LR) #경사하강법처리를 한다. gradient 값을 초기화한다.







In [76]:
for i in range(STEPS):
    #추론
    preds = model(inputs)
    #오차 계산
    loss = mse_loss_fn(preds,targets)
    # gradient 계산
    loss.backward()
    #파라미터 (weights,bias)값들을 업데이트 한다.
    optimizer.step()
    #파라미터의 grad 값 초기화
    optimizer.zero_grad()
    
    #10 steps 당 loss를 출력한다.
    
    if i % 10 ==0 or i == (STEPS-1):
        print(f"Step: {i} - loss:{loss.item()}") #tensor 객체.item() : 스칼라나 원소가 1개인 tensor의 값을 추출한다.
        
#이 코드들을 보고 전체적으로 몇 번을 할 지 파악할 수 있다.    
#오차가 줄어들 수록, loss 값이 감소하는 폭이 줄어든다.

Step: 0 - loss:35.308128356933594
Step: 10 - loss:29.35744285583496
Step: 20 - loss:24.427528381347656
Step: 30 - loss:20.341524124145508
Step: 40 - loss:16.954574584960938
Step: 50 - loss:14.146974563598633
Step: 60 - loss:11.819591522216797
Step: 70 - loss:9.890228271484375
Step: 80 - loss:8.290839195251465
Step: 90 - loss:6.965029716491699
Step: 99 - loss:5.966813087463379


In [74]:
print("학습 전 파라미터:")
print(weights)
print(bias)

학습 전 파라미터:
tensor([[ 1.5410, -0.2934],
        [-2.1788,  0.5684],
        [-1.0845, -1.3986]], requires_grad=True)
tensor([0.4033, 0.8380], requires_grad=True)


In [79]:
print("학습 후 파라미터:")
print(weights)
print(bias)

#여러가지 값들이 바뀐 것을 볼 수 있다.
#결과 강수량이 더 많은 영향을 주고 있다. 강수량이 각 과일에 주는 영향은 동일하다.

학습 후 파라미터:
tensor([[-0.3720, -0.2423],
        [ 0.8995,  0.9039],
        [ 0.5544,  0.6273]], requires_grad=True)
tensor([0.3984, 0.8511], requires_grad=True)


In [81]:
pred_value = model(inputs)

In [82]:
pred_value

tensor([[ 57.3486,  70.7001],
        [ 81.1847,  98.4942],
        [120.7241, 137.2814],
        [ 21.6454,  38.2148],
        [ 99.8916, 114.8202]], grad_fn=<AddBackward0>)

In [83]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# pytorch built-in 모델을 사용해 Linear Regression 구현

In [42]:
import torch
import torch.nn as nn #모델들을 제공하는 모듈이다.

In [43]:
inputs = torch.tensor([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype=torch.float32)

In [44]:
targets = torch.tensor([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype=torch.float32)

## nn.Linear
Pytorch는 nn.Linear 클래스를 통해 Linear Regression 모델을 제공한다.  
nn.Linear에 입력 feature의 개수와 출력 값의 개수를 지정하면 random 값으로 초기화한 weight와 bias들을 생성해 모델을 구성한다.

In [45]:
##Linear(input feature 개수, output 개수)
model = nn.Linear(3,2) 


## weight와 bias를 조회한다.  값은 랜덤으로 만든다. 
print(model.weight)
print(model.bias)



Parameter containing:
tensor([[-0.0146, -0.1694,  0.1242],
        [-0.0215, -0.1172,  0.2497]], requires_grad=True)
Parameter containing:
tensor([-0.3907, -0.3694], requires_grad=True)


In [46]:
#loss 함수 정의

#혹은 torch.nn.functional.mse_loss() 함수를 쓰기도 한다.
loss_fn = nn.MSELoss()


In [47]:
#optimizer 정의

optimizer = torch.optim.SGD(model.parameters(),lr=0.0001) #경사하강법을 계산해 주는 것이다. lr은 학습률이다.
#([최적화대상-모델의 파라미터])

In [48]:
##학습전에 추론 --->오차 계산

#추론
pred = model(inputs)
pred




tensor([[ -7.4607,   0.9457],
        [ -8.6709,   3.3408],
        [-17.1500,  -3.4612],
        [ -4.5634,   1.6366],
        [ -8.9600,   4.3742]], grad_fn=<AddmmBackward0>)

In [49]:
targets #정답이다. 위의 pred의 출력값과 잘 비교해보자.

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [50]:
#오차가 났으니 오차 계산을 하자.

loss = loss_fn(pred,targets) #(모델예측결과,정답)
loss

tensor(9116.2744, grad_fn=<MseLossBackward0>)

## Optimizer와 Loss 함수 정의
- torch.optim 모듈에 다양한 Optimizer 클래스가 구현되있다. 그 중에서 Adam를 사용한다.
- torch.nn 또는 torch.nn.functional 모듈에 다양한 Loss 함수가 제공된다. 이중 mse_loss() 를 사용한다.

## Model Train
주어진 epoch 만큼 학습하는 `fit`  함수를 정의한다.

In [58]:
def fit(num_epochs: "몇 번 반복할지",model:"학습시킬모델",loss_fn:"오차함수",optim:"옵티마이저",inputs:"입력데이터",targets:"출력데이터"):
    #친절하게 다 정의한다.
    for epoch in range(num_epochs):
        #지정한 횟수만큼 반복을 한다.
        #1. 추론
        pred = model(inputs)
        #2. 오차 계산
        loss = loss_fn(pred,targets)
        
        #3. gradient 계산
        loss.backward()
        
        #4.파라미터 업데이트
        optim.step()
        
        #5.계산된 gradient값을 초기화한다.
        optim.zero_grad()
        
        ####loss(결과) 출력
        if epoch % 10 == 0 or epoch == (num_epochs-1):
            print(f"{epoch}/{num_epochs}:train loss: {loss.item():.5f}")
    
    

In [59]:
#실제로 함수들을 적용해보자.
#가면 갈수록 오차가 많이 줄어드는 것을 알 수 있다.
fit(100,model,loss_fn,optimizer,inputs,targets)

0/100:train loss: 3779.40942
10/100:train loss: 151.17966
20/100:train loss: 36.67197
30/100:train loss: 13.09365
40/100:train loss: 6.30169
50/100:train loss: 4.05732
60/100:train loss: 3.11103
70/100:train loss: 2.57364
80/100:train loss: 2.19489
90/100:train loss: 1.89894
99/100:train loss: 1.68045


In [60]:
#학습 후 모델 추론 결과를 확인

p= model(inputs)
p

tensor([[ 57.1823,  70.3610],
        [ 81.6451,  99.8332],
        [119.9420, 134.7774],
        [ 21.5037,  37.5874],
        [100.6195, 117.2753]], grad_fn=<AddmmBackward0>)

In [61]:
l = loss_fn(p,targets)
l.item()

1.6584752798080444